FROM 9.5 슬림 : 데비안

LABEL  "com.github.actions.name" = "Hello World" 
LABEL  "com.github.actions.description" = "표준 출력" 
LABEL  "에 인수 쓰기 com.github.actions.icon" = "mic" 
LABEL  " com.github.actions.color " = "purple "

LABEL  "저장소" = "http://github.com/octocat/hello-world" 
LABEL  "홈페이지" = "http://github.com/actions" 
LABEL  "메인테이너" = "Octocat <octocat@github.com> "

entrypoint.sh /entrypoint.sh를 추가 하십시오.
 ENTRYPOINT [ "/entrypoint.sh" ]
